export const seedSkills = [
  { name: "HTML/CSS", category: "frontend" },
  { name: "JavaScript", category: "frontend" },
  { name: "TypeScript", category: "frontend" },
  { name: "React", category: "frontend" },
  { name: "Next.js", category: "frontend" },
  { name: "Vue.js", category: "frontend" },
  { name: "Tailwind CSS", category: "frontend" },
  { name: "Node.js", category: "backend" },
  { name: "Python", category: "backend" },
  { name: "C#", category: "backend" },
  { name: "Java", category: "backend" },
  { name: "FastAPI", category: "backend" },
  { name: "ASP.NET Core", category: "backend" },
  { name: "Spring Boot", category: "backend" },
  { name: "PostgreSQL", category: "backend" },
  { name: "SQL", category: "backend" },
  { name: "Azure", category: "cloud" },
  { name: "AWS", category: "cloud" },
  { name: "Docker", category: "cloud" },
  { name: "CI/CD", category: "cloud" },
  { name: "Git", category: "cloud" },
  { name: "Data Science", category: "data" },
  { name: "Machine Learning", category: "data" },
  { name: "Power BI", category: "data" },
  { name: "Excel/Sheets", category: "data" },
  { name: "UI/UX Design", category: "design" },
  { name: "Figma", category: "design" },
  { name: "Cybersecurity", category: "specialist" },
  { name: "Networking", category: "specialist" },
  { name: ".NET MAUI", category: "specialist" },
] as const;
